# ExtendedChat Configuration

command-tab-enabled: true
command-tab-mode: "blacklist" # blacklist or whitelist
command-tab-list:
  - "plugins"
  - "pl"
  - "bukkit:plugins"
  - "bukkit:pl"

chat-format-enabled: true
chat-format: "<white><player_name><dark_gray>» <white><message>"
chat-formats-enabled: false
chat-formats:
  - permission: "extendedchat.format.vip"
    weight: 100
    format: "<gold>[VIP] <player_name><dark_gray>» <white><message>"
  - permission: "extendedchat.format.member"
    weight: 10
    format: "<white><player_name><dark_gray>» <white><message>"

staff-chat-enabled: true
staff-chat-format: "<red>[STAFF] <player_name> <dark_gray>» <white><message>"
staff-chat-permission: "extendedchat.staff"

private-messages-enabled: true
private-msg-sent-format: "<gray>You → <gold><target_name> <white><message>"
private-msg-received-format: "<gold><sender_name> <gray>→ You <white><message>"

filters-enabled: true
anti-spam-enabled: true
anti-spam-cooldown: 1.0

anti-link-enabled: true
anti-link-regex-list:
  - "(https?://|www\\.)[\\w\\-._~:/?#\\[\\]@!$&'()*+,;=%]+"
  - "(?i)(discord\\.gg|minecraft\\.server\\.me)"
anti-link-whitelist:
  - "hypixel.net"
  - "cubecraft.net"
  - "mc-market.org"

color-enabled: true
color-gradients-enabled: true
default-name-color: "<white>"
default-message-color: "<white>"